POST http://localhost:3000/animais   
Content-Type: application/json

{
    "id": 1,
    "nome": "Dick",
    "idade": 9
}

###

GET http://localhost:3000/animais

###

PUT http://localhost:3000/animais/1
Content-Type: application/json

{
    "id": 2,
    "nome": "Skol",
    "idade": 6
}

###

DELETE http://localhost:3000/animais/1