POST http://localhost:3000/animais   
Content-Type: application/json

{
    "id": 6,
    "nome": "Mel",
    "idade": 1
}

###

GET http://localhost:3000/animais

###

PUT http://localhost:3000/animais/5
Content-Type: application/json

{
    "id": 4,
    "nome": "Farinha",
    "idade": 2
}

###

DELETE http://localhost:3000/animais/6